controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

blog_list:
    path: /blog.{_format}/{page}
    controller: App\Controller\BlogController::list
    defaults:
        page: 1
    format: html 
    requirements:
        page: '\d+'

blog_show:
    path: /blog/{slug}
    controller: App\Controller\BlogController::show
